"use strict";

var app = app || {};

app.level = 1;
app.lifes = 3;
app.pause = false;
app.points = 0;
app.maxSpeed = 400;
app.allItems = new Map();
app.LEVEL_UP_POINTS = 100;

//function to choose randomly between three numbers
app.randomNum = function(){
    var num = Math.floor((Math.random()*10)/3);
    return num;
};

//get random X coordanate for items (gems, or rocks)
app.heartCreationRate = function() {
    var num = 0;
    switch(Math.floor(Math.random()*10)){
        case 0:
            num = 0;
            break;
        case 1:
            num = 101;
            break;
        case 2:
            num = 202;
            break;
        case 3:
            num = 303;
            break;
        case 4:
            num = 404;
            break;
        case 5:
            num = 505;
            break;
        case 6:
            num = 606;
            break;
        case 7:
            num = 707;
            break;
        case 8:
            num = 808;
            break;
        case 9:
            num = 909;
            break;
    }
    return num;
};

app.levelUp = function() {
    var that = this;
    //update counters, display them on screen
    this.level++;
    $("#level").text("Level " + that.level);
    this.points += this.LEVEL_UP_POINTS;
    $("#points").text(that.points + " pts");

    //when level up, delete all gems and hearts displayed
    this.deleteGemsHearts();

    //using random number generated by heartCreationRate to randomly generate
    //hearts items.

    if (this.heartCreationRate()%5===0) {
        var heart = new Heart();
        this.allItems.set(heart.key, heart);
    }

    if (this.level<=8 || (this.level>=25 && this.level%5 === 0)) {
        this.createEnemies();
    }

    if((this.level>=10 && this.level<26) && this.level%2===0) {
        var rock = new Rock();
        this.allItems.set(rock.key, rock);
    }

    if (this.level>=10 && this.level%2===1) {
        var gem = new Gem();
        this.allItems.set(gem.key, gem);
    }

    if (this.level > 30) {
        this.maxSpeed = 500;
    }

    //if max level reached, won Modal is displayed. Player can
    //choose to start a new game
    if (this.level === 40) {
        this.pause = true;
        $("#wonModal").modal('show');
        $(".restart").click(function() {
                that.restart();
            });
    }
};

//manage life counter, this function receives
//a boolean value
app.addLife = function(up) {
    //lifes counter is displayed to player as a list of hearts
    var elements = $("ul").children();
    var elem;
    var that = this;
    //plus one life when player catches a heart item
    if (up === true) {
        if (this.lifes < 3) {
            elem = elements[this.lifes];
            //refactor hearts counter displayed to user
            $(elem).toggleClass('fontawesome-heart-empty fontawesome-heart');
            this.lifes++;
        }
    } else { //minus one life when player collides with bug
        this.lifes--;
        elem = elements[this.lifes];
        //refactor hearts counter displayed to user
        $(elem).toggleClass('fontawesome-heart fontawesome-heart-empty');

        //game over, show game over modal, player can choose to start a new game
        if (this.lifes === -1) {
            this.pause = true;
            //choose an image to display on modal
            this.gameOverImg();
            $("#gameOverModal").modal('show');
            $(".restart").click(function() {
                that.restart();
            });
        }
    }
};

//function that resets variables with initial values
app.restart = function() {
    var that = this;

    this.level = 1;
    this.lifes = 3;
    this.points = 0;
    this.maxSpeed = 400;
    this.allItems.clear();
    this.allEnemies = [];
    this.player.x = 404;
    this.player.y = 390;

    //reset info displayed on screen
    $("#level").text("Level " + that.level);
    $("#points").text(that.points + " pts");

    var elements = $("ul").children();
    //couldn't iterate with forEach loop
    for (var i = 0; i < 3; i++) {
        var heartElem = elements[i];

        //when used toggleClass found a bug
        $(heartElem).removeClass('fontawesome-heart-empty');
        $(heartElem).addClass('fontawesome-heart');
    }

    this.startGame();

};

//function used to select character
app.startGame = function() {
    var selected = null;
    var that = this;

    $("#startModal").modal('show');

    $(".char-elem").click(function() {

        //remove and add classes to show player which caracter was selected
        if (selected !== null) {
            $(selected).removeClass('char-selected');
        }

        //define new player sprite according to choosen caracter
        that.player.sprite = $(this).attr('src');
        $(this).addClass('char-selected');
        selected = $(this);
    });

    $("#startButton").off('click').on('click', function() {
        //Bug-found function being called more than once,
        //if was used to assure only one enemy is created each time a new game
        //starts
        that.createEnemies();
        that.pause = false;
    });
};

//function to choose random game over images
app.gameOverImg = function() {
    var imageGameOver = $("#game-over-img");
    var r = this.randomNum();
    switch(r){
        case 0:
            $(imageGameOver).attr('src', 'images/unagi.jpg');
            break;
        case 1:
            $(imageGameOver).attr('src', 'images/give-up.jpg');
            break;
        case 2:
            $(imageGameOver).attr('src', 'images/tugging.jpg');
            break;
        default:
            $(imageGameOver).attr('src', 'images/waste.jpg');
    }
};

var GameObject = function() {};

GameObject.prototype.getY = function() {
    var num = 0;
    switch(app.randomNum()) {
        case 0:
            num = 60;
            break;
        case 1:
            num = 143;
            break;
        default:
            num = 226;
    }
    return num;
};

var Character = function() {
    GameObject.call(this);
};

Character.prototype = Object.create(GameObject.prototype);
Character.prototype.constructor = Character;

Character.prototype.render = function() {
    ctx.drawImage(Resources.get(this.sprite), this.x, this.y);
};

Character.prototype.getX = function() {
    var num = 0;
    switch(app.randomNum()){
        case 0:
            num = -150;
            break;
        case 1:
            num = -350;
            break;
        default:
            num = -550;
    }
    return num;
};


Character.prototype.getSpeed = function() {
    return Math.floor(Math.random() * (app.maxSpeed - 100 + 1)) + 100;
};

// Enemies our player must avoid
var Enemy = function() {
    Character.call(this);

    // Variables applied to each of our instances go here,
    // we've provided one for you to get started
    this.x = this.getX();
    this.y = this.getY();
    this.speed = this.getSpeed();
    // The image/sprite for our enemies, this uses
    // a helper we've provided to easily load images
    this.sprite = 'images/enemy-bug.png';
};

Enemy.prototype = Object.create(Character.prototype);
Enemy.prototype.constructor = Enemy;

// Update the enemy's position, required method for game
// Parameter: dt, a time delta between ticks
Enemy.prototype.update = function(dt) {
    // You should multiply any movement by the dt parameter
    // which will ensure the game runs at the same speed for
    // all computers.
    this.x = this.x + this.speed*dt;

    //if enemie crossed screen get new x and y coordenates
    //also get a new value for speed
    if (this.x >= 1010) {
        this.x = this.getX();
        this.y = this.getY();
        this.speed = this.getSpeed();
    }
};

// Now write your own player class
// This class requires an update(), render() and
// a handleInput() method.

var Player = function() {
    Character.call(this);
    this.PLAYER_X_INIT_COORD = 404;
    this.PLAYER_Y_INIT_COORD = 390;
    this.x = this.PLAYER_X_INIT_COORD;
    this.y = this.PLAYER_Y_INIT_COORD;
    //xplus and y plus used to manage rock interactivity
    this.xplus = 0;
    this.yplus = 0;
    this.sprite = 'images/char-boy.png';
    this.PLAYER_RIGTH_LIMIT = 909;
    this.PLAYER_LEFT_LIMIT = 0;
    this.PLAYER_Y_MOVE = 83;
    this.PLAYER_X_MOVE = 101;

};

Player.prototype = Object.create(Character.prototype);
Player.prototype.constructor = Player;

//handle player's playing area borders and collision with items
Player.prototype.update = function() {
    //player reaches water
    if (this.y === -25) {
        this.x = this.PLAYER_X_INIT_COORD;
        this.y = this.PLAYER_Y_INIT_COORD;
        app.levelUp();
    }

    //contain player into playing area
    if (this.y >= this.PLAYER_Y_INIT_COORD) {
        this.y = this.PLAYER_Y_INIT_COORD;
    }

    if (this.x <= this.PLAYER_LEFT_LIMIT) {
        this.x = this.PLAYER_LEFT_LIMIT;
    }

    if (this.x >= this.PLAYER_RIGTH_LIMIT) {
        this.x = this.PLAYER_RIGTH_LIMIT;
    }

    //manage rock, gem and heart items
    if (app.allItems.size > 0) {
        app.allItems.forEach(function(item) {
            if (this.x === item.x && (item.y - this.y <= 5 && item.y - this.y >= 0)) {

                if (item instanceof Rock) {
                    //if item is a Rock, return player to previous position
                    //giving the efect of player being blocked by rock
                    this.x = this.x - this.xplus;
                    this.y = this.y - this.yplus;
                } else {
                    if (item instanceof Gem) {
                        //if item is gem, add points and delete gem from map
                        app.points = app.points + item.GEM_VALUE;
                        $("#points").text(app.points + " pts");
                        app.allItems.delete(item.key);
                    } else {
                        if (item instanceof Heart) {
                            app.addLife(true);
                            app.allItems.delete(item.key);
                        }
                    }
                }
            }
        }, this);
    }
};

//moves player through the playing area
Player.prototype.handleInput = function(key) {
    this.xplus = 0;
    this.yplus = 0;

    switch (key) {
        case 'left':
            this.x = this.x - this.PLAYER_X_MOVE;
            this.xplus = - this.PLAYER_X_MOVE;
            break;
        case 'up':
            this.y = this.y - this.PLAYER_Y_MOVE;
            this.yplus = - this.PLAYER_Y_MOVE;
            break;
        case 'right':
            this.x = this.x + this.PLAYER_X_MOVE;
            this.xplus = this.PLAYER_X_MOVE;
            break;
        case 'down':
            this.y = this.y + this.PLAYER_Y_MOVE;
            this.yplus = this.PLAYER_Y_MOVE;
            break;
    }
};

//Rocks, Gems and Hearts
var Item = function() {
    GameObject.call(this);
    this.x = this.getXCoord();
    this.y = this.getY();
    //create key to store item on map
    this.key = this.x.toString()+this.y.toString();
    this.checkCoords();
};

Item.prototype = Object.create(GameObject.prototype);
Item.prototype.constructor = Item;

//validates that another item doesn't have the same position
//if it does, new x and y coordenates are generated
//as well as a new key
Item.prototype.checkCoords = function() {

        while (app.allItems.has(this.key)) {
            this.x = this.getXCoord();
            this.y = this.getY();
            this.key = this.x.toString()+this.y.toString();
        }
};

Item.prototype.getXCoord = function() {
    var num = 0;
    switch(Math.floor(Math.random()*10)){
        case 0:
            num = 0;
            break;
        case 1:
            num = 101;
            break;
        case 2:
            num = 202;
            break;
        case 3:
            num = 303;
            break;
        case 4:
            num = 404;
            break;
        case 5:
            num = 505;
            break;
        case 6:
            num = 606;
            break;
        case 7:
            num = 707;
            break;
        case 8:
            num = 808;
            break;
        case 9:
            num = 909;
            break;
    }
    return num;
};

Item.prototype.render = function() {
    ctx.drawImage(Resources.get(this.sprite), this.x, this.y);
};

var Rock = function() {
    this.sprite = 'images/Rock.png';
    Item.call(this);
};

Rock.prototype = Object.create(Item.prototype);
Rock.prototype.constructor = Rock;

var Gem = function() {
    this.randomColor();
    Item.call(this);
};

Gem.prototype = Object.create(Item.prototype);
Gem.prototype.constructor = Gem;

//randomly generate a different color gem
Gem.prototype.randomColor = function(){
    var num = app.randomNum();

    if (num === 0) {
        this.sprite = 'images/Gem-Blue.png';
        this.GEM_VALUE = 300; 
    }else {
        if (num === 1) {
            this.sprite = 'images/Gem-Orange.png';
            this.GEM_VALUE = 200;
        }else {
            this.sprite = 'images/Gem-Green.png';
            this.GEM_VALUE = 100;
        }
    }
};

var Heart = function() {
    this.sprite = 'images/Heart.png';
    Item.call(this);
};

Heart.prototype = Object.create(Item.prototype);
Heart.prototype.constructor = Heart;

//delete all Gems and Hearts that are in map
app.deleteGemsHearts = function() {
    this.allItems.forEach(function(item) {
        if (item instanceof Gem || item instanceof Heart) {
            this.allItems.delete(item.key);
        }
    }, this);
};

// Now instantiate your objects.
// Place all enemy objects in an array called allEnemies
// Place the player object in a variable called player
app.allEnemies = [];
app.player = new Player();

app.createEnemies = function() {
    this.allEnemies.push(new Enemy());
};

// This listens for key presses and sends the keys to your
// Player.handleInput() method. You don't need to modify this.
document.addEventListener('keyup', function(e) {
    var allowedKeys = {
        37: 'left',
        38: 'up',
        39: 'right',
        40: 'down',
        32: 'space'
    };

    //show or hide pause game modal
    if (e.keyCode===32) {
        app.pause = !app.pause;
        if (app.pause === false) {
            $("#pauseModal").modal('hide');
        } else {
            $("#pauseModal").modal('show');
        }
    }
    //block player to move caracter when game is paused
    if (app.pause===false) {
        app.player.handleInput(allowedKeys[e.keyCode]);
    }
});
